### PR TITLE
Fix mine distribution

### LINKED ISSUE #2: Make mines more dispersed
The mines tend to clump up at the top like this:
```
>>> test.print_board()
*....**..*
....*..*..
....****..
.*.**....*
...*.***..
..........
..........
..........
..........
..........
```

It'd be awesome if we could come up with a method to help them spread out better.

### PR DESCRIPTION
**Pull request by quiksand**
1. Changed generate_new_board() method
  *  First, generates a string of zeroes equal to row*col - mines 
  *  Then, injects mines into string at random intervals up to number of mines specified
  *  Finally, splits string into rows of equal column length specified
  *  Local variables for rows and cols for readability
  *  Local mine variable for global protection- self.mines will be needed for other methods
  *  Fixes #2 - Mines appear much more evenly dispersed now
  *  Mine count no longer random, but customizable
2. Updated __init__()
  * Now includes default values for rows, columns, and mines as arguments
  * Added global vars in class for these default values
3. Modified print_board()
 *  Now can take up to two arguments, defaults provided for easy calling
 * Arguments are for replacing blank space and mine chars
 * Not totally necessary but improves readability, imo

### CODE REVIEW

**Comment by mhelmetag** [comment]
Do work!! Nice! We may also be able to make an array of empty spaces (minus the number of mines). Add on an array of mines spaces. And just call `random.shuffe(array)` then split the array into rows.

**Comment by mhelmetag** [comment]
I think you're good to merge if you're happy with it. I'll check it out more when I get home and I may ask for your thoughts on a refactor using `random.shuffle()` and `array.slice()`.

**Comment by quiksand** [comment]
shuffle looks awesome. I wasn't aware of that one. It looks like it could simplify the generator for sure

**Comment by mhelmetag** [comment]
There's almost always a built-in ;)

**Pull request merged**
